### ISSUE TITLE
Add Prettier overrides for YAML files

### ISSUE THREAD

**Issue by stijnklomp** [stijnklomp/linting-formatting-config#5]
```yaml
"overrides": [
  {
    "files": ["*.yml", ".yaml"],
    "options": {
      "useTabs": false
    }
  }
]
 ```
